# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9a1bf8f4c2115147af9c9e4c68ef585f7b6ebdf044b85d5fce6de5f368f2b9ae107055298b34b2b2f5dbb7b19d6685858b907faa3ec75fc17330f72ff6e87b0

test:
  secret_key_base: b8ef5682f1927721c02512b86842de8a47626ba228963342df9faf0f8d5bbcb932e3cc9f45e971e051ef965bd56aa15a83cc446022632b65527af6b3be613936

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
